import Link from "next/link";
import type { Metadata } from "next";
import { COMPANY_NAME, SUPPORT_EMAIL, GOVERNING_LAW_STATE, LEGAL_LAST_UPDATED } from "@/lib/legal";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms for using Business Formation Coach.",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-2xl px-4 py-12">
      <Link href="/" className="text-sm font-medium text-slate-500 hover:text-slate-900">
        ← Business Formation Coach
      </Link>
      <h1 className="mt-4 text-2xl font-bold text-slate-900">Terms of Service</h1>
      <p className="mt-1 text-sm text-slate-400">Last updated {LEGAL_LAST_UPDATED}</p>

      <div className="mt-8 space-y-8 text-sm leading-relaxed text-slate-700">
        <section>
          <h2 className="text-base font-semibold text-slate-900">What this is</h2>
          <p className="mt-2">
            Business Formation Coach is a free educational guide built by {COMPANY_NAME}. It's not legal, tax, or
            financial advice, and using it doesn't create an attorney-client, accountant-client, or advisory
            relationship of any kind. Every stage that touches something high-stakes (entity structure, taxes,
            compliance deadlines) says so and points you to a licensed professional for your specific situation —
            that guidance is part of these terms, not just a suggestion.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-slate-900">The AI-generated business plan</h2>
          <p className="mt-2">
            The business plan document is generated by an AI model from the answers you provide. It can be wrong,
            outdated, or miss context only you know. Review it yourself before using it for anything that matters —
            especially before submitting it to a lender — and consider the paid human review if it's going somewhere
            that counts.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-slate-900">Affiliate links and referrals</h2>
          <p className="mt-2">
            Some links in the guide are affiliate links, and some sections point to {COMPANY_NAME}'s own paid
            services — both are disclosed where they appear. We recommend based on fit, not on what pays the most;
            using an affiliate link never changes the price you pay.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-slate-900">Your account</h2>
          <p className="mt-2">
            You're responsible for keeping your password secure and for what happens under your account. You can
            delete your account at any time from your account page — that's permanent and can't be undone.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-slate-900">Paid plan review</h2>
          <p className="mt-2">
            If you purchase a paid review of your business plan, that's a one-time service performed by a person, not
            an automated process — turnaround time and scope are described at checkout. Payment is processed by
            Stripe under their own terms.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-slate-900">No warranty</h2>
          <p className="mt-2">
            The guide is provided as-is. We work to keep the content accurate and current, but regulations change —
            always verify anything time-sensitive (deadlines, fees, requirements) directly with the relevant
            government agency before relying on it.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-slate-900">Governing law</h2>
          <p className="mt-2">These terms are governed by the laws of {GOVERNING_LAW_STATE}.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-slate-900">Contact</h2>
          <p className="mt-2">Questions about these terms: {SUPPORT_EMAIL}.</p>
        </section>

        <p className="border-t border-slate-200 pt-4 text-xs text-slate-400">
          Written to be accurate to how the app actually works, not as a substitute for legal advice — have these
          terms reviewed by an attorney before relying on them, particularly the governing-law section above.
        </p>
      </div>
    </div>
  );
}
